### ISSUE TITLE
#OOM problem while running the model.fit

### ISSUE THREAD

**Issue by AnushriPrao** [maulikchevli/DepthEstimationTransferLearning#1]
Hello,

I was trying your code without changing anything at first. I also ran the code mounting the google drive. But there is an Out Of Memory(OOM) issue when I start the training. Could you please help me with this issue?

Also, are there any colab settings I am supposed to do before running the code? Looking forward to hearing from you soon.

System specification
4gb RAM
ubuntu 20.0 LTS
256GB SSD

The error message:

ResourceExhaustedError:  OOM when allocating tensor with shape[8,168,240,320] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node gradient_tape/depth_estimate_4/decoder_4/upscale_block_19/up4_convA/Conv2D/Conv2DBackpropInput (defined at <ipython-input-50-91d08e546323>:17) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_train_function_236938]

Errors may have originated from an input operation.
Input Source operations connected to node gradient_tape/depth_estimate_4/decoder_4/upscale_block_19/up4_convA/Conv2D/Conv2DBackpropInput:
 depth_estimate_4/decoder_4/upscale_block_19/up4_convA/Conv2D/ReadVariableOp (defined at /content/drive/My Drive/Dense_depth/model.py:16)

Function call stack:
train_function

**Comment by maulikchevli** [comment]
Hi, reducing the `batch_size` or image size should resolve this memory exhaustion error.

**Comment by AnushriPrao** [comment]
Thank you for your response.
Yes, I saw that answer in many posts. I will try that. But, did you ever
faced the same problem? Because I see that even you are running it on
google colab with drive. I don't know what is wrong with it when I am
running it. Is there anything related to the hardware I am missing?

Regards,
Anushri P Rao

**Comment by maulikchevli** [comment]
I think I didn't run into this problem as I maybe using the 25GB RAM GPU variant. Unfortunately, I just read that [Google has stopped offering free higher RAM runtimes](https://www.reddit.com/r/GoogleColab/comments/hcsliy/colab_ram_limit/).

Pertaining to colab settings, there is no need to change any except runtime type for quicker execution. Also, mounting Gdrive isn't required to run the notebook.

**Comment by AnushriPrao** [comment]
OK, I reduced the batch size to 6. Now it is running fine. I had to mount
the Google drive because the link that you have written to download the
NYUv2 train dataset zip is not working. So I had to download the zip
somewhere else and store it in my drive to connect and run.

But I really appreciate your quick response. Thanks again for your help.

Best regards,
Anu

**Comment by maulikchevli** [comment]
Great its working now!

I see the Author of this paper has moved the data to https://s3-eu-west-1.amazonaws.com/densedepth/nyu_data2.zip. I will update it.

Closing this issue. Feel free to re-open it if you run into memory problems.

**Comment by AnushriPrao** [comment]
Sure. Thank you.

Have a great weekend

Best regards,
Anushri P Rao
